# Windpower Function

P = 0.5 * p * A * C_p * V^3

# Calculates the amount of power, in Watts, of a certain windmill.

# Parameters 
# @param P, wind power.
# @param p, air density in kg/m^3 assumed default is at sea level, 1.23 kg/m^3.
# @param A, pi*r^2. Rotor swept area (m^2). 
# @param C_p, power coeffiecient = electricity produced by wind turbine / total energy available in the wind, default at = 0.4.
# @param V = velocity of wind, 6 - 25m/s is where utility scale wind power is generated.

windpower = function(A, V, p=1.23, C_p=0.4) {
  P = 0.5 * p * A * C_p * V^3
  return(P)
}

# This function helps to calculate power output of wind. The power output is generated by wind turbines. You can plug in the Rotor swept area and velocity of the wind into the function and the function output is power generated, in Watts. 







